# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0005_auto_20170914_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='upwd',
            field=models.CharField(default='', max_length=20),
        ),
    ]
